lmdb build fix

diff --git a/install-deps b/install-deps
--- a/install-deps
+++ b/install-deps
@@ -76,9 +76,8 @@ if [[ `uname` == 'Darwin' ]]; then
     brew install git readline cmake wget qt
     brew install libjpeg imagemagick zeromq graphicsmagick openssl
     brew link readline --force
-    brew install caskroom/cask/brew-cask
     brew cask install xquartz
-    brew remove gnuplot
+    brew list -1 | grep -q "^gnuplot\$" && brew remove gnuplot
     brew install gnuplot --with-wxmac --with-cairo --with-pdflib-lite --with-x11 --without-lua
 
 elif [[ "$(uname)" == 'Linux' ]]; then
@@ -92,7 +91,7 @@ elif [[ "$(uname)" == 'Linux' ]]; then
     elif [[ -r /etc/redhat-release ]]; then
         DIST_VERS=( $( cat /etc/redhat-release ) ) # make the file an array
         DISTRO="${DIST_VERS[0],,}" # get the first element and get lcase
-        VERS="${DIST_VERS[2]}" # get the third element (version)
+        VERSION="${DIST_VERS[2]}" # get the third element (version)
     elif [[ -r /etc/lsb-release ]]; then
         DIST_VERS="$( ( . /etc/lsb-release &>/dev/null
                         echo "${DISTRIB_ID,,} $DISTRIB_RELEASE") )"
@@ -143,15 +142,21 @@ elif [[ "$(uname)" == 'Linux' ]]; then
             echo '==> Ubuntu version not supported.'
             exit 1
         elif [[ $ubuntu_major_version -lt '14' ]]; then
-            sudo add-apt-repository -y ppa:chris-lea/zeromq
-            sudo add-apt-repository -y ppa:chris-lea/node.js
+            sudo -E add-apt-repository -y ppa:chris-lea/zeromq
+            sudo -E add-apt-repository -y ppa:chris-lea/node.js
         elif [[ $ubuntu_major_version -lt '15' ]]; then
-            sudo add-apt-repository -y ppa:jtaylor/ipython
+            sudo -E add-apt-repository -y ppa:jtaylor/ipython
         else
             sudo apt-get install -y software-properties-common \
                 libgraphicsmagick1-dev nodejs npm libfftw3-dev sox libsox-dev \
                 libsox-fmt-all
         fi
+
+        sudo apt-get update
+        sudo apt-get install -y build-essential gcc g++ curl \
+            cmake libreadline-dev git-core libqt4-dev libjpeg-dev \
+            libpng-dev ncurses-dev imagemagick libzmq3-dev gfortran \
+            unzip gnuplot gnuplot-x11 ipython
 
         gcc_major_version=$(gcc --version | grep ^gcc | awk '{print $4}' | \
                             cut -c 1)
@@ -160,18 +165,15 @@ elif [[ "$(uname)" == 'Linux' ]]; then
             sudo apt-get install -y gcc-4.9 libgfortran-4.9-dev g++-4.9
         fi
 
-        sudo apt-get update
-        sudo apt-get install -y build-essential gcc g++ curl \
-            cmake libreadline-dev git-core libqt4-core libqt4-gui \
-            libqt4-dev libjpeg-dev libpng-dev ncurses-dev \
-            imagemagick libzmq3-dev gfortran unzip gnuplot \
-            gnuplot-x11 ipython
-
         if [[ $ubuntu_major_version -lt '14' ]]; then
             # Install from source after installing git and build-essential
             install_openblas || true
         else
             sudo apt-get install -y libopenblas-dev liblapack-dev
+        fi
+
+        if [[ $ubuntu_major_version -lt '15' ]]; then
+            sudo apt-get install libqt4-core libqt4-gui
         fi
 
     elif [[ $distribution == 'elementary' ]]; then
@@ -190,10 +192,10 @@ elif [[ "$(uname)" == 'Linux' ]]; then
                 libgraphicsmagick1-dev nodejs npm libfftw3-dev sox libsox-dev \
                 libsox-fmt-all
 
-            sudo add-apt-repository -y ppa:jtaylor/ipython
+            sudo -E add-apt-repository -y ppa:jtaylor/ipython
         else
-            sudo add-apt-repository -y ppa:chris-lea/zeromq
-            sudo add-apt-repository -y ppa:chris-lea/node.js
+            sudo -E add-apt-repository -y ppa:chris-lea/zeromq
+            sudo -E add-apt-repository -y ppa:chris-lea/node.js
         fi
         sudo apt-get update
         sudo apt-get install -y "${target_pkgs[@]}"
@@ -234,24 +236,33 @@ elif [[ "$(uname)" == 'Linux' ]]; then
                                 qt-devel qtwebkit-devel sox-plugins-freeworld \
                                 ipython
             install_openblas || true
-        elif [[ $fedora_major_version == '22' ||  $fedora_major_version == '23'  ]]; then
+        elif [[ $fedora_major_version == '22' ||  $fedora_major_version == '23' ]]; then
             #using dnf - since yum has been deprecated
             #sox-plugins-freeworld is not yet available in repos for F22
-            sudo dnf install -y cmake curl readline-devel ncurses-devel \
-            			gcc-c++ gcc-gfortran git gnuplot unzip \
-            			nodejs npm libjpeg-turbo-devel libpng-devel \
-            			ImageMagick GraphicsMagick-devel fftw-devel \
-            			sox-devel sox qt-devel qtwebkit-devel \
-            			python-ipython czmq czmq-devel
+            sudo dnf install -y make cmake curl readline-devel ncurses-devel \
+                                gcc-c++ gcc-gfortran git gnuplot unzip \
+                                nodejs npm libjpeg-turbo-devel libpng-devel \
+                                ImageMagick GraphicsMagick-devel fftw-devel \
+                                sox-devel sox qt-devel qtwebkit-devel \
+                                python-ipython czmq czmq-devel
+            install_openblas || true
+        elif [[ $fedora_major_version == '24' ]]; then
+            # Using DNF, but no longer installing npm since that comes with nodejs now.
+            sudo dnf install -y make cmake curl readline-devel ncurses-devel \
+                                gcc-c++ gcc-gfortran git gnuplot unzip \
+                                nodejs libjpeg-turbo-devel libpng-devel \
+                                ImageMagick GraphicsMagick-devel fftw-devel \
+                                sox-devel sox qt-devel qtwebkit-devel \
+                                python-ipython czmq czmq-devel
             install_openblas || true
         else
-            echo "Only Fedora 20 or Fedora 22 is supported for now, aborting."
+            echo "Only Fedora 20-24 are supported for now, aborting."
             exit 1
         fi
     elif [[ $distribution == 'centos' ]]; then
         if [[ $centos_major_version == '7' ]]; then
             sudo yum install -y epel-release # a lot of things live in EPEL
-            sudo yum install -y cmake curl readline-devel ncurses-devel \
+            sudo yum install -y make cmake curl readline-devel ncurses-devel \
                                 gcc-c++ gcc-gfortran git gnuplot unzip \
                                 nodejs npm libjpeg-turbo-devel libpng-devel \
                                 ImageMagick GraphicsMagick-devel fftw-devel \
@@ -281,16 +292,21 @@ elif [[ "$(uname)" == 'Linux' ]]; then
         install_openblas || true
     fi
 
+elif [[ "$(uname)" == 'FreeBSD' ]]; then
+    pkg install ImageMagick cmake curl fftw3 git gnuplot libjpeg-turbo \
+        libzmq3 ncurses node npm openblas openssl png py27-ipython \
+        py27-pip qt4-corelib qt4-gui readline unzip
+
 else
     # Unsupported
     echo '==> platform not supported, aborting'
     exit 1
 fi
 
-ipython_exists=$(command -v ipython)
+ipython_exists=$(command -v ipython) || true
 if [[ $ipython_exists ]]; then {
     ipython_version=$(ipython --version|cut -f1 -d'.')
-    if [[ $ipython_version != 2 && $ipython_version != 3 && $ipython_version != 4 ]]; then {
+    if [[ $ipython_version -lt 2 ]]; then {
         echo 'WARNING: Your ipython version is too old.  Type "ipython --version" to see this.  Should be at least version 2'
     } fi
 } fi
